name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: "0 */1 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ 3628d515-5d8a-4187-8b4b-0d17ab5f1090 }}
          GH_TOKEN: ${{ 71faa5cc3b91ccbc1c6eb0d385395c75b5b11bb4 }}
